#
# API params
api:
    address:
        host: "0.0.0.0"
        port: "8081"
        database: "sss-computing"
    params:
        ship_id: "2"
        project_id: NULL
#
model:
    name: "sofia"
    midel_x: 65.25
#
# Thread-pool params
thread-pool:
    size: 15    

